version: 1.23.7.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
environment:
  nuget_user:
    secure: kWtlS49bKmP0IFXmdvDHmxGI8mS0xQGrwiJoco9nYtA=
  nuget_password:
    secure: Pzvx2CQjxp8eCBP+nFI2eg==
  appveyor_rdp_password:
    secure: Pzvx2CQjxp8eCBP+nFI2eg==
configuration:
  - Debug
  - Release
services: iis

# skip branch build if there is an active pull request
skip_branch_with_pr: true

init:
- cmd: echo Project - %APPVEYOR_PROJECT_NAME%
- cmd: echo Worker image - %APPVEYOR_BUILD_WORKER_IMAGE%
- cmd: echo Branch - %APPVEYOR_REPO_BRANCH%
- cmd: echo Author - %APPVEYOR_REPO_COMMIT_AUTHOR%
- cmd: echo Commit - %APPVEYOR_REPO_COMMIT%
#- cmd: echo (%APPVEYOR_REPO_COMMIT_MESSAGE%)
#- cmd: echo (%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%)
- cmd: echo Platform - %PLATFORM%
- cmd: echo Configuration - %CONFIGURATION%
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

nuget:
  account_feed: false
  project_feed: false

install:
- cmd: C:\projects\spectre\scripts\restore_nugets.bat
- ps: C:\projects\spectre\scripts\InstallNode.ps1

build_script:
- cmd: msbuild "C:\projects\spectre\src\Spectre.sln" /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% /m /verbosity:quiet /p:DeployOnBuild=true /p:PublishProfile=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: C:\projects\spectre\scripts\build_ng_client.bat %CONFIGURATION%
after_build:
- ps: C:\projects\spectre\scripts\BindPageToIisAndCreateDataDir.ps1 -AppVeyor
- cmd: C:\projects\spectre\scripts\package_project.bat DiviK Spectre.DivikWpfClient
- cmd: C:\projects\spectre\scripts\package_web_project.bat WebAPI Spectre
- cmd: C:\projects\spectre\scripts\package_angular_client.bat

test_script:
- cmd: C:\projects\spectre\scripts\test_native_code.bat
- cmd: C:\projects\spectre\scripts\test_dotnet.bat --except Algorithm
- cmd: C:\projects\spectre\scripts\test_frontend.bat
- cmd: C:\projects\spectre\scripts\test_frontend_e2e.bat

artifacts:
- path: DiviK-$(configuration).zip
  name: DivikExecutables
- path: WebClient-$(configuration).zip
  name: WebClient
- path: WebAPI-$(configuration).zip
  name: WebAPI

deploy:
- provider: GitHub
  release: Spectre-v$(appveyor_build_version)
  auth_token:
    secure: dQadz+smqtuxpigZ/LmrUKyA0uVZ5kgljKntyoHEdobTycbeMywbfmiJtZPNcOQ2
  artifact: DivikExecutables
  draft: true
- provider: GitHub
  release: Spectre-v$(appveyor_build_version)
  auth_token:
    secure: dQadz+smqtuxpigZ/LmrUKyA0uVZ5kgljKntyoHEdobTycbeMywbfmiJtZPNcOQ2
  artifact: WebClient
  draft: true
- provider: GitHub
  release: Spectre-v$(appveyor_build_version)
  auth_token:
    secure: dQadz+smqtuxpigZ/LmrUKyA0uVZ5kgljKntyoHEdobTycbeMywbfmiJtZPNcOQ2
  artifact: WebAPI
  draft: true

on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- cmd: C:\projects\spectre\scripts\upload-frontend-test-results.bat

notifications:
# this publishes to Continuous Integration channel in Glip
- provider: Webhook
  url:
    secure: V16hjhyXfcLNyhNUih9v1Lb4wDly5r6CNNufciMrvllwt0m0rkguf6o4DY7pbdKia/vJGmErvQLdEW0MkzqsAhLWiPY7+Z6qvzFjweP8xNg=
  method: POST
  content_type: application/json
  body: >-
    {
      "icon": "https://www.appveyor.com/assets/img/appveyor-logo-256.png",
      "activity": "AppVeyor",
      "title": "Build {{buildVersion}} **{{#failed}}failed{{/failed}}{{#passed}}passed{{/passed}}** in {{duration}}",
      "body": "{{#isPullRequest}}Pull request: [#{{pullRequestId}}](https://github.com/spectre-team/spectre/pull/{{pullRequestId}})\n{{/isPullRequest}}Branch: [{{branch}}](https://github.com/spectre-team/spectre/tree/{{branch}})\nCommit: [{{commitId}} {{commitMessage}}](https://github.com/spectre-team/spectre/commit/{{commitId}})\nAuthor: {{commitAuthor}}\n[Build details]({{buildUrl}})"
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
